@host = http://localhost:4000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJhc2Vzb3IiLCJpYXQiOjE3NDU2ODU1NzcsImV4cCI6MTc0NTY4OTE3N30.BNUuR9n5-3Q4D5bZ1iPY6ttaPuggWbmAtyr9pjNvO7M

###
# testing server
GET {{host}}

###
# login
POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "asesor@example.com",
    "password": "password123"
}

###
# Fichar entrada
POST {{host}}/api/attendance/punch-in
Content-Type: application/json
Authorization: Bearer {{token}}

###
# Fichar salida
POST {{host}}/api/attendance/punch-out
Content-Type: application/json
Authorization: Bearer {{token}}

###
# Historial de jornadas
GET {{host}}/api/attendance
Authorization: Bearer {{token}}

###
# Resumen de horas por días
GET {{host}}/api/attendance/summary
Authorization: Bearer {{token}}

###
# Get me
GET {{host}}/auth/me
Authorization: Bearer {{token}}